### ISSUE TITLE
与源代码结果比较

### ISSUE THREAD

**Issue by hellosher** [ShenhanQian/Lane_Detection-Instance_Segmentation-Tensorflow#1]
请问您的代码较源代码结果有提升吗，应该怎么训练呢，我在训练源代码的时候发现准确率一直较低，无法到达0.9，请问您有遇到这样的问题吗，该怎么修改呢？

**Comment by ShenhanQian** [comment]
抱歉没有及时关注到你的提问。

我在调试[MaybeSheWill的代码](https://github.com/MaybeShewill-CV/lanenet-lane-detection)（之后简称**M代码**）的过程中，Accuracy只有大约0.7，我提出了Issue，MaybeSheWill表示模型参数是在其他数据集上Pretrain过的，没有进一步就如何从随机初始化的参数训练出相近性能的模型提出更多建议。我个人对**M码**的数据集的划分方式存在疑问。之后我做了很多尝试，但Accuracy仍没有显著提升。我个人有如下几点观察和思考：

1. **M码**提供的`train_lanenet.py`中，Accuracy被用来衡量二类分割（Binary Segmentation）的性能，根据代码实现，Accuracy实际上是对Ground Truth Mask的查全率(Recall)（之后简称`acc1`）。而在Tusimple Benchmark的Lane Detection Task中，对Accuracy的定义是对数据集原始标注点的的查全率（之后简称`acc2`），二者不能混为一谈。

之后的实验表明，尽管`acc1`只有0.7，但经过聚类和拟合，仍能获得超过0.9的`acc2`。因此，无需拘泥于`acc1`。


2. Tusimple Benchmark数据集的原始标注方式是点坐标，需要基于这些坐标生成为分割网络生成Ground Truth图像。在原图像中，车道线宽度是近大远小的，而论文方法用固定宽度折线连接各点以生成车道线的Mask图像。这种做法存在先天不足，其Mask的标注较为粗糙，因此分割性能指标只能用作参考性能指标。

**M代码**中，车道线的Mask是用OpenCV中的折线端函数绘制的，折线宽度是代码作者自己设定的。若想提高`acc1`，可以在生成数据集时增大Ground Truth图像中的折线的线宽，经实验，当线宽设为15 pix时，`acc1`就已经十分接近1。但这种做法没有实际意义，还会使多条车道线的Mask在接近灭点处重叠、连通，造成拟合偏差。


4. Tusimple数据集对车道线的标注存在模糊性。在一部分图像中，道路上没有车道线标记，仅有路缝作为车道间的界限；在另一部分图像中，同时有车道线标记和路缝，而两者之间存在一定的偏移。因此网络预测的车道线Mask相对于Ground Truth Mask普遍存在少量偏移，在mask线宽较窄的情况下，预测的mask与GT mask之间的重叠面积比会较小，导致分割结果的查全率较低。


综上，**M码**中定义的Accuracy(`acc1`)并不是Lane Detection任务中真正关注的指标，但其数值不高是可以解释的。

**Comment by hellosher** [comment]
@ShenhanQian 非常感谢您的回复，也希望能学习一下您的代码^_^

**Comment by hellosher** [comment]
@ShenhanQian冒昧叨扰您，您会尽快开源您的代码吗？感觉现有的开源代码很乱^~^

**Comment by ShenhanQian** [comment]
@hellosher 正在努力清理，预计需要一周。

**Comment by hellosher** [comment]
@ShenhanQian 大佬，新的一周，继续等你的代码😂

**Comment by ShenhanQian** [comment]
已完成初步整理，README文档有待完善。
[Lane_Detection-An_Instance_Segmentation_Approach](https://github.com/ShenhanQian/Lane_Detection-An_Instance_Segmentation_Approach)

**Comment by ShenhanQian** [comment]
@hellosher 
已初步完成整理，代码测试过了，详见README.md中的QuickStart部分。
README.md的内容之后会继续完善。
[Lane_Detection-An_Instance_Segmentation_Approach](https://github.com/ShenhanQian/Lane_Detection-An_Instance_Segmentation_Approach)
